-- Ejecuta este script en Supabase SQL Editor para guardar las solicitudes
-- del formulario principal de ResinArte.

create table if not exists public.personalizaciones (
  id bigint generated by default as identity primary key,
  proyecto text not null default 'ResinArte',
  nombre text not null,
  email text not null,
  imagen_inspiracion text,
  texto_pieza text,
  color_preferido text,
  tamano text,
  comentarios text,
  fecha_solicitud timestamptz not null default now(),
  estado text not null default 'pendiente',
  created_at timestamptz not null default now()
);

alter table public.personalizaciones enable row level security;

drop policy if exists "Permitir registros publicos de ResinArte" on public.personalizaciones;

create policy "Permitir registros publicos de ResinArte"
on public.personalizaciones
for insert
to anon
with check (
  proyecto = 'ResinArte'
  and length(trim(nombre)) > 0
  and email ~* '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$'
);
